### ISSUE TITLE
Updating AppBadge seems to break with twitter on macOS because inject code is returning NaN

### ISSUE THREAD

**Issue by plugandplay** [yafp/ttth#182]
Hello,

When I try to set up my Twitter account, ttth displays this error in a loop as soon as I am logged in.

```
TypeError: Error processing argument at index 0, conversion failure from null
    at App.setBadgeCount (electron/js2c/browser_init.js:6976:31)
    at IpcMain.<anonymous> (/Applications/ttth.app/Contents/Resources/app.asar/main.js:641:47)
    at IpcMain.emit (events.js:203:13)
    at IpcMain.EventEmitter.emit (domain.js:476:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3849:15)
    at WebContents.emit (events.js:203:13)
    at WebContents.EventEmitter.emit (domain.js:476:20)
    at WebContents.emitter.emit (/Applications/ttth.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:55:20)
    at WebContents.topLevelDomainCallback (domain.js:131:23)
```

![macos_ttth_20200424_132059](https://user-images.githubusercontent.com/67605/80209801-02674d80-8633-11ea-8a22-1e73ff344551.png)

---

ttth 1.8.20200228
Electron 7.1.11
darwin 18.7.0
Locale: fr

**Comment by yafp** [comment]
@plugandplay 
thanks for the issue/report.
to be honest - i am not using twitter myself  in ttth. 
I'll take a look into it tomorrow and see if i can reproduce your issue.

Am i guessing right that the error is displayed after finishing the service configuration?

**Comment by plugandplay** [comment]
After finishing the service configuration, I was able to see the Twitter login page.
The bug occurred right after I filled the login form.

**Comment by yafp** [comment]
@plugandplay 
i just set up a twitter service on my developing machine.
On the first look it works as expected.
I can login without.

What i do notice here is that the inject code which is used to detect unread messages seems to fail.
This means there is a green Badge showing "NaN" in the service tab.

But in general it just works.

Some questions
* Regarding service url: did you change the service url in the service configuration window? By default it is set to https://mobile.twitter.com
* Regarding os: your issue is tagged as darwin 18.7. Is that a current macOS?

What might be helpful is:
* start ttth and remove the service
* close ttth
* start ttth and press F12 to open the dev console. (shows logging)
* switch to the settings tab and re-add the twitter service 
* paste the content of the dev console here.

**Comment by yafp** [comment]
![ttth_twitter](https://user-images.githubusercontent.com/67605/80061975-e7adaf80-8532-11ea-8ceb-aa4bf1e3334c.png)

**Comment by yafp** [comment]
non-problem related - but as i am curious: 
are you using any other services? If so - do they work as expected and how is your experience in general with ttth?

**Comment by plugandplay** [comment]
Well, the error is displayed in loop as soon as I restarted ttth. It has been difficult to remove the Twitter service.

To answer your questions:
- I didn't change the service URL, or anything else.
- My OS  is macOS Mojave (Version 10.14.6).
- Before I tried the Twitter service, I have set up WhatsApp without any problem.
After removing the Twitter service, I still don't have a problem with WhatsApp.
I started using ttth yesterday so I am not an experienced user yet. I really like the idea of a FOSS app to replace those of many vendors.

Here are the console logs with errors after I add the Twitter service again:
```
/Applications/ttth.app/Contents/Resources/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 08:43:25.531 › [ Renderer ] updateServiceBadge ::: New unread count for service _twitter_j9Dfgb5D5AdIK5CMnzhSFhw7_ is: _NaN_.
/Applications/ttth.app/Contents/Resources/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 08:43:25.533 › [ Renderer ] updateTrayIconStatus ::: Unread messages count of _twitter_j9Dfgb5D5AdIK5CMnzhSFhw7_ is: NaN
/Applications/ttth.app/Contents/Resources/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 08:43:25.534 › [ Renderer ] updateTrayIconStatus ::: Overall unread message count for all enabled services is: _NaN_.
```

**Comment by yafp** [comment]
@plugandplay 
i am not yet sure why this happens - as i havent it tested yet on MacOS

What you might test is:
* open ttth
* switch to the settings tab
* press the folder button below the listed configured services. This open a directory where a .json file is located for each of your defined services
* Now close ttth
* Create a backup of `twitter_SOMERANDOMSTRIN.json` somewhere outside of this folder (i.e. your desktop)
* Open the original  `twitter_SOMERANDOMSTRIN.json` in your favorite text editor
* Remote the path to the injectcode

The following is just an example
from: 
`{"type":"twitter","name":"Twitter","icon":"fab fa-twitter","url":"https://mobile.twitter.com/","injectCode":"./js/ttth/services/twitter/twitter_inject.js","serviceEnableStatus":true,"userAgentDefault":"","userAgentCustom":""}`

to
`{"type":"twitter","name":"Twitter","icon":"fab fa-twitter","url":"https://mobile.twitter.com/","injectCode":"","serviceEnableStatus":true,"userAgentDefault":"","userAgentCustom":""}`

* save the file
* start ttth

Please report back if that changes something.

**Comment by yafp** [comment]
@plugandplay 
i guess i understood where the problem is coming from.

Some time ago i've added code which:
* tries to detect if the operating system of the user is supporting AppBadges (a badge next to the application icon)
* if it is supported - ttth tries to use it

You as mac user have an environment where my code is realizing that AppBadges are technically supported - and therefor tries to use it.
The function which i am using there seems to be deprecated.

I'll let you know when it is fixed - in the meantime you can't use twitter in ttth on osx (sorry)
